### PR TITLE
navigation-fixes:

### LINKED ISSUE #175: pageLimit option does not work well for navigation which using tags filering
There are few issues related to tag filtering:

1. Project has a flat structure - all items copied into '/items' folder and for building navigation used tag filtering. Now if limit amount of items only first column will have items.

2. Auto-generated link "All specs XX" - shows total for all items, but not filtered 

screen shot 2015-08-27 at 16 11 01

Example:

```
<script type="text/javascript">
  define('sourceModules/inlineOptions', {
      modulesOptions : {
          globalNav : {
              pageLimit: 5
          }
      }
  });
</script>

<div class="source_subhead">
  <h1>My Collection</h1>
</div>


<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="widget">
    <h2 class="source_catalog_title"><a href="/collections/widgets">Widgets</a></h2>
    <p>My widgets.</p>
  </div>
</div>

<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="module">
    <h2 class="source_catalog_title"><a href="/collections/modules">Modules</a></h2>
    <p>My modules.</p>
  </div>
</div>

<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="container">
    <h2 class="source_catalog_title"><a href="/collections/containers">Containers</a></h2>
    <p>My containers.</p>
  </div>
</div>
```

### PR DESCRIPTION
**Pull request by cheshirsky**
- multiple tags support is added #176
- templates extending ability #174
- specs validation is fixed #175

### CODE REVIEW

**Comment by operatino** [comment]
Js Hint fails

File: assets/js/modules/globalNav.js [hunk 1]
```diff
@@ -24,6 +24,7 @@ define([
         "showPreviews": false,
         "sortType": "sortByDate",
         "sortDirection":"forward",
+        "delimeter": " ",
```
Comment (operatino) [inline assets/js/modules/globalNav.js]: I think it should be comma by default. Could you please also add some info about this in generated nav documentation https://github.com/sourcejs/Source/blob/master/docs/data-nav/readme.md?

**Comment by operatino** [comment]
Do you use specs validation plugin in Backbase?

**Comment by operatino** [comment]
Is this somehow related to external templates issue? https://github.com/sourcejs/Source/issues/174

Could you please next time use more commits, so it would be easier to track specific changes?

**Comment by cheshirsky** [comment]
> Is this somehow related to external templates issue? #174

yes

> Could you please next time use more commits, so it would be easier to track specific changes?

Yes, for sure.

> Do you use specs validation plugin in Backbase?

No, I don't think so.

> Js Hint fails

Fixed. But checks are failed. By the way, I can't see any reasons or explanations.

**Comment by operatino** [comment]
Now CasperJS tests are failing, seems like there's a JS error on the page in clean SourceJS set-up.

```
Error:    TypeError: 'undefined' is not an object (evaluating 'obj['tag'].indexOf')
file:     http://127.0.0.1:8080/source/assets/js/modules/globalNav.js
line:     155
function: 
FAIL JS errors found: TypeError: 'undefined' is not an object (evaluating 'obj['tag'].indexOf')
#    type: fail
#    file: test/casperjs/common.js:40
#    code: test.fail("JS errors found: "+ error.msg);
#    subject: false
```

File: docs/data-nav/readme.md [hunk 2]
```diff
@@ -66,7 +66,7 @@ If there is no description, or you want to leave custom text, just use this extr
 
 ## Filtering by tag
 
-As it's possible to define different tags for specs in `info.json` files (more in [docs](/docs/info-json/)), we can use them to filter custom navigation tree.
+As it's possible to define different tags for specs in `info.json` files (more in [docs](/docs/info-json/)), we can use them to filter custom navigation tree. It is also possible to define more than one tag for each spec. You can use "," as a delimeter, e.g. `templates,navigation`. Delimeter is also configurable (you can change it in `globalNav` options object).
```
Comment (operatino) [inline docs/data-nav/readme.md]: Is it going to work with `templates, navigation`? Having a spec in between?

**Comment by cheshirsky** [comment]
> Now CasperJS tests are failing, seems like there's a JS error on the page in clean SourceJS set-up.

I can't see checking problems :(

File: assets/js/modules/globalNav.js [hunk 3]
```diff
@@ -144,8 +149,11 @@ define([
      * @returns {Boolean} true if spec shoud be skipped.
```
Comment (operatino) [inline assets/js/modules/globalNav.js]: Correct JSDom, first param is now not only a String, but could also be an array.

File: assets/js/modules/globalNav.js [hunk 4]
```diff
@@ -144,8 +149,11 @@ define([
...
      */
     var skipSpec = function(navListCat, obj) {
+        obj = obj || {};
         // obj["cat"] is an array; if cat has needed value
-        var inArray = !!obj["tag"] && obj["tag"].indexOf(navListCat) > -1;
+        var inArray = !!obj["tag"] && typeof(navListCat) === "string"
+            ? !!~obj["tag"].indexOf(navListCat)
+            : !!obj["tag"] && _.reduce(navListCat, function(inArray, item) { return inArray && !!~obj['tag'].indexOf(item); }, true);
```
Comment (operatino) [inline assets/js/modules/globalNav.js]: Please break this down into separate functions, inline code is unreadable.

File: assets/js/modules/globalNav.js [hunk 5]
```diff
@@ -144,8 +149,11 @@ define([
      * @returns {Boolean} true if spec shoud be skipped.
      */
     var skipSpec = function(navListCat, obj) {
+        obj = obj || {};
         // obj["cat"] is an array; if cat has needed value
-        var inArray = !!obj["tag"] && obj["tag"].indexOf(navListCat) > -1;
+        var inArray = !!obj["tag"] && typeof(navListCat) === "string"
```
Comment (operatino) [inline assets/js/modules/globalNav.js]: It's better to check if it's an array.

File: assets/js/modules/globalNav.js [hunk 6]
```diff
@@ -267,7 +277,13 @@ define([
         if(target && target.length === 1) {
             var url = catalogHeaderURL && catalogHeaderURL.length && navOptions.useHeaderUrlForNavigation
                 ? catalogHeaderURL : navListDir;
-            var itemsDocFragment = this.getNavigationItemsList(data, url, filter);
+            var itemsDocFragment = this.getNavigationItemsList(
+                _.reduce(data, function(result, item) {
```
Comment (operatino) [inline assets/js/modules/globalNav.js]: Please move it to separate var, to make it more readable.

File: assets/js/modules/globalNav.js (hunk 4 above)
Comment (operatino) [inline assets/js/modules/globalNav.js]: Strip spaces in each tag item from array to support `"tag1, tag2"`

File: assets/js/modules/globalNav.js [hunk 7]
```diff
@@ -77,48 +80,50 @@ define([
...
-
-        sortList: _.template([
-            '<ul class="source_sort-list">',
-                '<li class="source_sort-list_li">Sort by&nbsp;</li>',
-                '<li class="source_sort-list_li"><a class="source_sort-list_a" id="sortByAlph" href="#sort=alph">alphabet</a></li>',
-                '<li class="source_sort-list_li">&nbsp;or&nbsp;</li>',
-                '<li class="source_sort-list_li"><a class="source_sort-list_a" id="sortByDate" href="#sort=date">date</a></li>',
-            '</ul>'
-        ].join(""))
+    GlobalNav.prototype.initTemplates = function() {
```
Comment (operatino) [inline assets/js/modules/globalNav.js]: Please add a short section in navigation docs about styling and changing templates.

File: assets/js/modules/globalNav.js (hunk 5 above)
Comment (cheshirsky) [inline assets/js/modules/globalNav.js]: why?

Comment (operatino) [inline assets/js/modules/globalNav.js]: If not string, then it could be an object/number etc, which will fail or produce unexpected output.

Comment (cheshirsky) [inline assets/js/modules/globalNav.js]: No, it can't. This is the internal function which is used with `string` or `string.split` (Array) as an argument.

File: assets/js/modules/globalNav.js (hunk 7 above)
Comment (cheshirsky) [inline assets/js/modules/globalNav.js]: Added

File: assets/js/modules/globalNav.js (hunk 3 above)
Comment (cheshirsky) [inline assets/js/modules/globalNav.js]: Done
